const strings=[['E',82.41],['A',110],['D',146.83],['G',196],['B',246.94],['e',329.63]];
let selected=0,audioCtx,osc,metroTimer,beat=1,bpm=90,micStream,analyser;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function activate(tab){$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===tab));$$('.dock-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
$$('.dock-item').forEach(b=>b.onclick=()=>activate(b.dataset.tab));
const grid=$('#stringGrid'); strings.forEach((s,i)=>{const b=document.createElement('button');b.textContent=s[0];b.onclick=()=>{selected=i;renderStrings();$('#ghostNote').textContent=s[0];$('#freqText').textContent=s[1].toFixed(2)+' Hz'};grid.appendChild(b)});
function renderStrings(){[...grid.children].forEach((b,i)=>b.classList.toggle('active',i===selected));} renderStrings();
function ctx(){return audioCtx||(audioCtx=new (window.AudioContext||window.webkitAudioContext)())}
$('#refBtn').onclick=()=>{const c=ctx(); if(osc) osc.stop(); osc=c.createOscillator(); const g=c.createGain(); osc.frequency.value=strings[selected][1]; osc.type='sine'; g.gain.setValueAtTime(.0001,c.currentTime); g.gain.exponentialRampToValueAtTime(.25,c.currentTime+.03); g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+1.15); osc.connect(g).connect(c.destination); osc.start(); osc.stop(c.currentTime+1.25)};
$('#micBtn').onclick=async()=>{try{const c=ctx(); micStream=await navigator.mediaDevices.getUserMedia({audio:true}); analyser=c.createAnalyser(); analyser.fftSize=2048; c.createMediaStreamSource(micStream).connect(analyser); $('#tunerStatus').textContent='Microfone ativo. Toque uma corda.'; detect();}catch(e){$('#tunerStatus').textContent='Não foi possível acessar o microfone.'}}
function detect(){if(!analyser)return; const data=new Float32Array(analyser.fftSize); analyser.getFloatTimeDomainData(data); const pitch=autoCorrelate(data,ctx().sampleRate); if(pitch>0){const target=strings[selected][1]; const cents=1200*Math.log2(pitch/target); $('#freqText').textContent=pitch.toFixed(1)+' Hz'; $('#needle').style.transform=`translateX(${Math.max(-115,Math.min(115,cents*2.2))}px)`; $('#tunerStatus').textContent=Math.abs(cents)<8?'Perfeito. Afinado.':cents<0?'Um pouco baixo. Aperte a corda.':'Um pouco alto. Afrouxe a corda.'} requestAnimationFrame(detect)}
function autoCorrelate(buf,sr){let SIZE=buf.length,rms=0;for(let i=0;i<SIZE;i++)rms+=buf[i]*buf[i];rms=Math.sqrt(rms/SIZE);if(rms<.01)return -1;let r1=0,r2=SIZE-1,thres=.2;for(let i=0;i<SIZE/2;i++)if(Math.abs(buf[i])<thres){r1=i;break}for(let i=1;i<SIZE/2;i++)if(Math.abs(buf[SIZE-i])<thres){r2=SIZE-i;break}buf=buf.slice(r1,r2);SIZE=buf.length;let c=new Array(SIZE).fill(0);for(let i=0;i<SIZE;i++)for(let j=0;j<SIZE-i;j++)c[i]+=buf[j]*buf[j+i];let d=0;while(c[d]>c[d+1])d++;let maxval=-1,maxpos=-1;for(let i=d;i<SIZE;i++)if(c[i]>maxval){maxval=c[i];maxpos=i}return sr/maxpos}
function clickSound(){const c=ctx(),o=c.createOscillator(),g=c.createGain();o.frequency.value=beat===1?1600:980;o.type='square';g.gain.setValueAtTime(.18,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.045);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.055)}
function tick(){clickSound();$('#beatMark').textContent=beat;$('#metroOrb').classList.add('hit');setTimeout(()=>$('#metroOrb').classList.remove('hit'),120);beat=beat%4+1}
$('#metroBtn').onclick=e=>{if(metroTimer){clearInterval(metroTimer);metroTimer=null;e.target.textContent='Iniciar'}else{tick();metroTimer=setInterval(tick,60000/bpm);e.target.textContent='Parar'}};
function setBpm(v){bpm=Math.max(40,Math.min(220,Number(v)));$('#bpmValue').textContent=bpm;$('#bpmSlider').value=bpm;if(metroTimer){clearInterval(metroTimer);metroTimer=setInterval(tick,60000/bpm)}}
$('#bpmSlider').oninput=e=>setBpm(e.target.value);$('#minusBtn').onclick=()=>setBpm(bpm-5);$('#plusBtn').onclick=()=>setBpm(bpm+5);
const items={"C maior":[60,54,48],"G maior":[56,50,44],"D maior":[58,52,46],"A menor":[62,56,50],"E menor":[54,48,42],"Escala maior":[66,62,58,54,50,46,42],"Escala menor":[64,61,58,54,51,47,44]};
const list=$('#libraryList');Object.keys(items).forEach((name,i)=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>drawScore(name);list.appendChild(b);if(i===0)b.classList.add('active')});
function drawScore(name){$('#scoreTitle').textContent=name;[...list.children].forEach(b=>b.classList.toggle('active',b.textContent===name));const svg=$('#scoreSvg');svg.innerHTML='';for(let i=0;i<5;i++){svg.innerHTML+=`<line x1="20" y1="${35+i*18}" x2="400" y2="${35+i*18}" stroke="white" opacity=".72"/>`} items[name].forEach((y,i)=>{svg.innerHTML+=`<ellipse class="note-dot" cx="${70+i*45}" cy="${y}" rx="11" ry="8" fill="white" style="animation-delay:${i*.06}s"/><line x1="${80+i*45}" y1="${y}" x2="${80+i*45}" y2="${y-42}" stroke="white"/>`})}
drawScore('C maior');
